"""add_do_not_contact_and_service_intervals

Revision ID: fc49f24c697f
Revises: c3d4e5f6a7b8
Create Date: 2026-05-11 09:41:30.176172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc49f24c697f'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('service_intervals',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interval_value', sa.Integer(), nullable=False),
    sa.Column('interval_unit', sa.Enum('km', 'days', 'months', name='interval_unit'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_intervals_team_id'), 'service_intervals', ['team_id'], unique=False)
    op.add_column('clients', sa.Column('do_not_contact', sa.Boolean(), nullable=True))
    op.execute("UPDATE clients SET do_not_contact = false WHERE do_not_contact IS NULL")
    op.alter_column('clients', 'do_not_contact', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'do_not_contact')
    op.drop_index(op.f('ix_service_intervals_team_id'), table_name='service_intervals')
    op.drop_table('service_intervals')
    # ### end Alembic commands ###
